/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSavingsRouteImport } from './routes/_app/savings'
import { Route as AppRecurringRouteImport } from './routes/_app/recurring'
import { Route as AppInvestmentsRouteImport } from './routes/_app/investments'
import { Route as AppDebtsRouteImport } from './routes/_app/debts'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppBudgetsRouteImport } from './routes/_app/budgets'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSavingsRoute = AppSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecurringRoute = AppRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentsRoute = AppInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtsRoute = AppDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accounts': typeof AppAccountsRoute
  '/budgets': typeof AppBudgetsRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/debts': typeof AppDebtsRoute
  '/investments': typeof AppInvestmentsRoute
  '/recurring': typeof AppRecurringRoute
  '/savings': typeof AppSavingsRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accounts': typeof AppAccountsRoute
  '/budgets': typeof AppBudgetsRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/debts': typeof AppDebtsRoute
  '/investments': typeof AppInvestmentsRoute
  '/recurring': typeof AppRecurringRoute
  '/savings': typeof AppSavingsRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/budgets': typeof AppBudgetsRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/debts': typeof AppDebtsRoute
  '/_app/investments': typeof AppInvestmentsRoute
  '/_app/recurring': typeof AppRecurringRoute
  '/_app/savings': typeof AppSavingsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transactions': typeof AppTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/dashboard'
    | '/debts'
    | '/investments'
    | '/recurring'
    | '/savings'
    | '/settings'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/dashboard'
    | '/debts'
    | '/investments'
    | '/recurring'
    | '/savings'
    | '/settings'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/_app/accounts'
    | '/_app/budgets'
    | '/_app/categories'
    | '/_app/dashboard'
    | '/_app/debts'
    | '/_app/investments'
    | '/_app/recurring'
    | '/_app/savings'
    | '/_app/settings'
    | '/_app/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/savings': {
      id: '/_app/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof AppSavingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recurring': {
      id: '/_app/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof AppRecurringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investments': {
      id: '/_app/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AppInvestmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debts': {
      id: '/_app/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof AppDebtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets': {
      id: '/_app/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDebtsRoute: typeof AppDebtsRoute
  AppInvestmentsRoute: typeof AppInvestmentsRoute
  AppRecurringRoute: typeof AppRecurringRoute
  AppSavingsRoute: typeof AppSavingsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppBudgetsRoute: AppBudgetsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDebtsRoute: AppDebtsRoute,
  AppInvestmentsRoute: AppInvestmentsRoute,
  AppRecurringRoute: AppRecurringRoute,
  AppSavingsRoute: AppSavingsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
